train_file: ['data/finetune/coco_karpathy/coco_karpathy_train.json']
val_file: 'data/finetune/coco_karpathy/coco_karpathy_val.json'
test_file: 'data/finetune/coco_karpathy/coco_karpathy_test.json'

image_root: 'images/coco/'
val_gt_file: 'data/finetune/coco_karpathy/coco_karpathy_val_gt.json'
test_gt_file: 'data/finetune/coco_karpathy/coco_karpathy_test_gt.json'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32

## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
num_dec_layers: 6
batch_size_train: 32
batch_size_test: 32
max_tokens: 40
label_smoothing: 0.1


## generation configs, following blip
max_length: 20
min_length: 5
num_beams: 3
prompt: 'a picture of '


## Other Settings
optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 1e-5, epochs: 5, num_warmup_steps: 0.1}
start_eval: 0  # epoch index

