train_file:  ["/dataset/vmengchu/X-VLM/download/extracted_folder_2/GeoText_Dataset_Offcial/train.json"]  #可以加入好多的train_set 的路径
# val_file: "/storage_fast/mchu/blip2/LAVIS/export/share/datasets/vision/university_caption419/annotation/high_valid.json" #'/storage_fast/mchu/blip2/LAVIS/export/share/datasets/vision/coco/annotations/coco_karpathy_val.json'
test_file: "/dataset/vmengchu/X-VLM/download/extracted_folder_2/GeoText_Dataset_Offcial/test_951_version.json" #"/storage_fast/mchu/Multi-model/geotext/GeoText/test/gallery_no_train/merged.json" #'/storage_fast/mchu/blip2/LAVIS/export/share/datasets/vision/coco/annotations/coco_karpathy_test.json'
image_root: '/dataset/vmengchu/X-VLM/download/extracted_folder_2/GeoText_Dataset_Offcial'


## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: '/dataset/vmengchu/X-VLM/download/data/bert'  # ['data/bert-base-uncased', 'data/roberta-base']



## Training
batch_size_train: 24
batch_size_test: 1
batch_size_test_text: 512
max_tokens: 50
embed_dim: 256
temp: 0.07
k_test: 256


## Other Settings
# optimizer: {opt: adamW, lr: 3e-6, weight_decay: 0.001, lr_mult: 2}
# schedular: {sched: linear, lr: 3e-6, epochs: 3, num_warmup_steps: 0.1}


optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 1, num_warmup_steps: 0.1}
