test_file: ['data/vlue_released/refcoco+_vlue_test.json']
image_root: 'images/marvl/'
vlue_test: True


## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
batch_size: 20
max_tokens: 40
careful_hflip: True  # first check whether 'left' or 'right' in captions






